DEPS_DIR          := $(CORE_DIR)/dependencies
LIBRETRO_COMM_DIR := $(CORE_DIR)/libretro-common

INCFLAGS = \
    -I$(LIBRETRO_COMM_DIR)/include \
    -I$(LIBRETRO_DIR) \
    -I$(CORE_DIR)/src/common \
    -I$(CORE_DIR)/src/common_netplay \
    -I$(CORE_DIR)/src/smw

CORE_DEFINE := -DNETWORK_DISABLED

FLAGS += -ffast-math -fno-strict-aliasing
FLAGS += -Wno-narrowing -Wno-unused-label
FLAGS += -Wno-misleading-indentation -Wno-unknown-pragmas
CXXFLAGS += -std=c++11 -fexceptions -fvisibility-inlines-hidden

# GCC 14 and Clang 16 reject incompatible pointer assignments by default. The
# SDL_image and SDL_mixer submodules declare their own prototypes for the
# libpng and libvorbis entry points they load, and those do not carry the
# const/restrict qualifiers the current headers use. Keep the mismatch a
# warning so the C sources build with modern toolchains. Apply this to C only:
# g++ rejects the option name.
C_WARNINGS := -Wno-incompatible-pointer-types

SOURCES_C =
SOURCES_CXX =

# ogg
SOURCES_C += \
    $(wildcard $(DEPS_DIR)/libogg/src/*.c)
FLAGS += -I$(DEPS_DIR)/libogg/include

# vorbisidec
SOURCES_C += \
    $(DEPS_DIR)/libvorbisidec-1.2.1/mdct.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/block.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/window.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/synthesis.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/info.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/floor1.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/floor0.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/vorbisfile.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/res012.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/mapping0.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/registry.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/codebook.c \
    $(DEPS_DIR)/libvorbisidec-1.2.1/sharedbook.c
FLAGS += -I$(DEPS_DIR)/libogg/include
CORE_DEFINE += -DVAR_ARRAYS -DHAVE_SYS_TYPES_H

# png
SOURCES_C += \
	$(wildcard $(DEPS_DIR)/libpng/*.c)
FLAGS += -I$(DEPS_DIR)/libpng

# zlib
SOURCES_C += \
	$(DEPS_DIR)/zlib/adler32.c \
	$(DEPS_DIR)/zlib/compress.c \
	$(DEPS_DIR)/zlib/crc32.c \
	$(DEPS_DIR)/zlib/deflate.c \
	$(DEPS_DIR)/zlib/infback.c \
	$(DEPS_DIR)/zlib/inffast.c \
	$(DEPS_DIR)/zlib/inflate.c \
	$(DEPS_DIR)/zlib/inftrees.c \
	$(DEPS_DIR)/zlib/trees.c \
	$(DEPS_DIR)/zlib/uncompr.c \
	$(DEPS_DIR)/zlib/zutil.c
FLAGS += -I$(DEPS_DIR)/zlib

# SDL
SOURCES_C += \
    $(wildcard $(DEPS_DIR)/SDL/src/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/audio/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/cdrom/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/cpuinfo/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/events/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/file/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/joystick/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/stdlib/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/thread/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/timer/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/video/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/audio/libretro/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/video/dummy/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/joystick/libretro/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/cdrom/dummy/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/timer/dummy/*.c) \
	$(wildcard $(DEPS_DIR)/SDL/src/loadso/dummy/*.c) \
    $(wildcard $(DEPS_DIR)/SDL/src/thread/generic/*.c)
FLAGS += -I$(DEPS_DIR)/SDL/include

# SDL_image
SOURCES_C += \
    $(DEPS_DIR)/SDL_image/IMG.c           \
    $(DEPS_DIR)/SDL_image/IMG_bmp.c       \
    $(DEPS_DIR)/SDL_image/IMG_gif.c       \
    $(DEPS_DIR)/SDL_image/IMG_jpg.c       \
    $(DEPS_DIR)/SDL_image/IMG_lbm.c       \
    $(DEPS_DIR)/SDL_image/IMG_pcx.c       \
    $(DEPS_DIR)/SDL_image/IMG_png.c       \
    $(DEPS_DIR)/SDL_image/IMG_pnm.c       \
    $(DEPS_DIR)/SDL_image/IMG_tga.c       \
    $(DEPS_DIR)/SDL_image/IMG_tif.c       \
    $(DEPS_DIR)/SDL_image/IMG_webp.c      \
    $(DEPS_DIR)/SDL_image/IMG_xcf.c       \
    $(DEPS_DIR)/SDL_image/IMG_xpm.c       \
    $(DEPS_DIR)/SDL_image/IMG_xv.c        \
    $(DEPS_DIR)/SDL_image/IMG_xxx.c
FLAGS += -I$(DEPS_DIR)/SDL_image
CORE_DEFINE += -DLOAD_PNG -DLOAD_BMP -DSDL_IMAGE_USE_COMMON_BACKEND

# SDL_mixer
SOURCES_C += \
    $(DEPS_DIR)/SDL_mixer/dynamic_flac.c  \
    $(DEPS_DIR)/SDL_mixer/dynamic_fluidsynth.c  \
    $(DEPS_DIR)/SDL_mixer/dynamic_mod.c  \
    $(DEPS_DIR)/SDL_mixer/dynamic_mp3.c  \
    $(DEPS_DIR)/SDL_mixer/dynamic_ogg.c  \
    $(DEPS_DIR)/SDL_mixer/effect_position.c  \
    $(DEPS_DIR)/SDL_mixer/effect_stereoreverse.c  \
    $(DEPS_DIR)/SDL_mixer/effects_internal.c  \
    $(DEPS_DIR)/SDL_mixer/fluidsynth.c  \
    $(DEPS_DIR)/SDL_mixer/load_aiff.c  \
    $(DEPS_DIR)/SDL_mixer/load_flac.c  \
    $(DEPS_DIR)/SDL_mixer/load_ogg.c  \
    $(DEPS_DIR)/SDL_mixer/load_voc.c  \
    $(DEPS_DIR)/SDL_mixer/mixer.c  \
    $(DEPS_DIR)/SDL_mixer/music_cmd.c  \
    $(DEPS_DIR)/SDL_mixer/music_flac.c  \
    $(DEPS_DIR)/SDL_mixer/music_mad.c  \
    $(DEPS_DIR)/SDL_mixer/music_mod.c  \
    $(DEPS_DIR)/SDL_mixer/music_modplug.c  \
    $(DEPS_DIR)/SDL_mixer/music_ogg.c  \
    $(DEPS_DIR)/SDL_mixer/music.c
FLAGS += -I$(DEPS_DIR)/SDL_mixer
CORE_DEFINE += -DOGG_MUSIC -DOGG_USE_TREMOR

# libretro-common
ifeq ($(STATIC_LINKING),1)
else
SOURCES_C += \
    $(LIBRETRO_COMM_DIR)/file/file_path.c \
    $(LIBRETRO_COMM_DIR)/file/file_path_io.c \
    $(LIBRETRO_COMM_DIR)/file/retro_dirent.c \
    $(LIBRETRO_COMM_DIR)/compat/compat_strl.c \
    $(LIBRETRO_COMM_DIR)/compat/fopen_utf8.c \
    $(LIBRETRO_COMM_DIR)/encodings/encoding_utf.c \
    $(LIBRETRO_COMM_DIR)/vfs/vfs_implementation.c \
    $(LIBRETRO_COMM_DIR)/streams/file_stream.c \
    $(LIBRETRO_COMM_DIR)/streams/file_stream_transforms.c \
    $(LIBRETRO_COMM_DIR)/string/stdstring.c \
    $(LIBRETRO_COMM_DIR)/time/rtime.c
endif

SOURCES_CXX += \
    $(LIBRETRO_DIR)/libretro.cpp \
    $(CORE_DIR)/src/common/dirlist.cpp \
    $(CORE_DIR)/src/common/eyecandy.cpp \
    $(CORE_DIR)/src/common/gfx.cpp \
    $(CORE_DIR)/src/common/global.cpp \
    $(CORE_DIR)/src/common/input.cpp \
    $(CORE_DIR)/src/common/linfunc.cpp \
    $(CORE_DIR)/src/common/map.cpp \
    $(CORE_DIR)/src/common/movingplatform.cpp \
    $(CORE_DIR)/src/common/path.cpp \
    $(CORE_DIR)/src/common/savepng.cpp \
    $(CORE_DIR)/src/common/sfx.cpp \
    $(CORE_DIR)/src/common/uicontrol.cpp \
    $(CORE_DIR)/src/common/uimenu.cpp \
    $(CORE_DIR)/src/common/FileIO.cpp \
    $(CORE_DIR)/src/common/FileList.cpp \
    $(CORE_DIR)/src/common/Game.cpp \
    $(CORE_DIR)/src/common/GameModeSettings.cpp \
    $(CORE_DIR)/src/common/GameValues.cpp \
    $(CORE_DIR)/src/common/MapList.cpp \
    $(CORE_DIR)/src/common/ObjectBase.cpp \
    $(CORE_DIR)/src/common/RandomNumberGenerator.cpp \
    $(CORE_DIR)/src/common/ResourceManager.cpp \
    $(CORE_DIR)/src/common/TilesetManager.cpp \
    $(CORE_DIR)/src/common/gfx/gfxFont.cpp \
    $(CORE_DIR)/src/common/gfx/gfxPalette.cpp \
    $(CORE_DIR)/src/common/gfx/gfxSDL.cpp \
    $(CORE_DIR)/src/common/gfx/gfxSprite.cpp \
    $(CORE_DIR)/src/common/gfx/SFont.cpp \
    $(CORE_DIR)/src/common/map/MapReader.cpp \
    $(CORE_DIR)/src/common/map/MapReader15xx.cpp \
    $(CORE_DIR)/src/common/map/MapReader16xx.cpp \
    $(CORE_DIR)/src/common/map/MapReader17xx.cpp \
    $(CORE_DIR)/src/common/map/MapReader18xx.cpp \
    $(CORE_DIR)/src/common/ui/MI_ImageSelectField.cpp \
    $(CORE_DIR)/src/common/ui/MI_MapField.cpp \
    $(CORE_DIR)/src/common/ui/MI_MapPreview.cpp \
    $(CORE_DIR)/src/common/ui/MI_SelectField.cpp \
    $(CORE_DIR)/src/common/ui/MI_SliderField.cpp \
    $(CORE_DIR)/src/smw/ai.cpp \
    $(CORE_DIR)/src/smw/gamemodes.cpp \
    $(CORE_DIR)/src/smw/net.cpp \
    $(CORE_DIR)/src/smw/objectgame.cpp \
    $(CORE_DIR)/src/smw/objecthazard.cpp \
    $(CORE_DIR)/src/smw/player.cpp \
    $(CORE_DIR)/src/smw/uicustomcontrol.cpp \
    $(CORE_DIR)/src/smw/world.cpp \
    $(CORE_DIR)/src/smw/GSGameplay.cpp \
    $(CORE_DIR)/src/smw/GSMenu.cpp \
    $(CORE_DIR)/src/smw/GSSplashScreen.cpp \
    $(CORE_DIR)/src/smw/ObjectContainer.cpp \
    $(CORE_DIR)/src/smw/menu/BonusWheelMenu.cpp \
    $(CORE_DIR)/src/smw/menu/GameSettingsMenu.cpp \
    $(CORE_DIR)/src/smw/menu/MainMenu.cpp \
    $(CORE_DIR)/src/smw/menu/MapFilterEditMenu.cpp \
    $(CORE_DIR)/src/smw/menu/MatchSelectionMenu.cpp \
    $(CORE_DIR)/src/smw/menu/ModeOptionsMenu.cpp \
    $(CORE_DIR)/src/smw/menu/OptionsMenu.cpp \
    $(CORE_DIR)/src/smw/menu/TeamSelectMenu.cpp \
    $(CORE_DIR)/src/smw/menu/TournamentScoreboardMenu.cpp \
    $(CORE_DIR)/src/smw/menu/TourStopMenu.cpp \
    $(CORE_DIR)/src/smw/menu/WorldMenu.cpp \
    $(CORE_DIR)/src/smw/menu/options/EyeCandyOptionsMenu.cpp \
    $(CORE_DIR)/src/smw/menu/options/GameplayOptionsMenu.cpp \
    $(CORE_DIR)/src/smw/menu/options/GraphicsOptionsMenu.cpp \
    $(CORE_DIR)/src/smw/menu/options/PowerupDropRatesMenu.cpp \
    $(CORE_DIR)/src/smw/menu/options/PowerupSettingsMenu.cpp \
    $(CORE_DIR)/src/smw/menu/options/ProjectileLimitsMenu.cpp \
    $(CORE_DIR)/src/smw/menu/options/ProjectileOptionsMenu.cpp \
    $(CORE_DIR)/src/smw/menu/options/SoundOptionsMenu.cpp \
    $(CORE_DIR)/src/smw/menu/options/TeamOptionsMenu.cpp \
    $(CORE_DIR)/src/smw/network/FileCompressor.cpp \
    $(CORE_DIR)/src/smw/network/NetConfigManager.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/BounceBlock.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/BreakableBlock.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/DonutBlock.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/FlipBlock.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/IO_Block.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/NoteBlock.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/OnOffSwitchBlock.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/PowerupBlock.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/SwitchBlock.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/ThrowBlock.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/ViewBlock.cpp \
    $(CORE_DIR)/src/smw/objects/blocks/WeaponBreakableBlock.cpp \
    $(CORE_DIR)/src/smw/objects/moving/MovingObject.cpp \
    $(CORE_DIR)/src/smw/objects/overmap/OverMapObject.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerAwardEffects.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerBurnupTimer.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerCape.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerCardCollection.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerCollisions.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerInvincibility.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerJail.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerKuriboShoe.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerOutOfArenaTimer.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerSecretCode.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerShield.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerSpinStatus.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerSuicideTimer.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerSuperStomp.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerTail.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerTanookiSuit.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerWarpStatus.cpp \
    $(CORE_DIR)/src/smw/player_components/PlayerWings.cpp \
    $(CORE_DIR)/src/smw/ui/MI_FrenzyModeOptions.cpp \
    $(CORE_DIR)/src/smw/ui/MI_NetRoomTeamSelect.cpp \
    $(CORE_DIR)/src/smw/ui/MI_PowerupSlider.cpp \
    $(CORE_DIR)/src/smw/ui/MI_StringScroll.cpp \
    $(CORE_DIR)/src/smw/ui/MI_TeamSelect.cpp \
    $(CORE_DIR)/src/smw/ui/NetworkListScroll.cpp
    
